# Generated by Django 6.0.6 on 2026-06-29 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('MTN', 'MTN'), ('Airtel', 'Airtel'), ('Glo', 'Globacom (Glo)'), ('9Mobile', '9Mobile')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity', models.CharField(default='30 Days', max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('fund', 'Wallet Funding'), ('purchase', 'Service Purchase'), ('refund', 'Failed Order Refund'), ('commission', 'Referral Commission')], max_length=20)),
                ('service', models.CharField(blank=True, choices=[('airtime', 'Airtime Top-Up'), ('data', 'Data Subscription'), ('electricity', 'Electricity Payment'), ('tv', 'Cable TV Subscription'), ('exam_pin', 'Exam Pin Purchase')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
